name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=9-s=%xi$8!a#8=*6poe3cf*wxb8quc83f81tv(6^&2h@@=6wuo
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID= zxqbiGChoMJHuhNhtpK3SfEY
      - PASSAGE_API_KEY= ZfdtxO2scK.zSQe87U14cWxFMasN9gxoKjRhja0n0zEXaQkv9XoeD0ghXaRvdOjdcXMVCkCOQic
    ports:
      - 8000:8000
